### ISSUE TITLE
Dubbele code

### ISSUE THREAD

**Issue by MarjoleinAardewijn** [StefanGerrits2/progressive-web-apps-1920#2]
https://github.com/StefanGerrits2/progressive-web-apps-1920/blob/8c5cd05c41c35b300ccf197a4ad7c5297e75e995/controllers/detail.js#L7

Ik zie dat je de `baseApiUrl` in meerdere files gebruikt. Misschien is het handig om deze in een aparte file te zetten, zodat wat meer modulair wordt en je dit maar op 1 plek hoeft aan te passen. Je zou deze bijv. als een extra variabele mee kunnen geven aan de functie.

**Comment by StefanGerrits2** [comment]
Vind ik zelf overbodig om daar een aparte file voor aan te maken, toch bedankt voor je feedback!
