### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by CountNick** [StefanGerrits2/progressive-web-apps-1920#5]
https://github.com/StefanGerrits2/progressive-web-apps-1920/blob/8c5cd05c41c35b300ccf197a4ad7c5297e75e995/controllers/modules/dataHelper.js#L39

This line of code is really long and a bit unreadable, you might want to find a fix for this?

**Comment by StefanGerrits2** [comment]
It puts beer around the same alcohol percentage in an array, might fix it if I've got time left.
